# This is a sample build configuration for Other.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

options:
  # Enable docker for the Pipeline
  docker: true
  
pipelines:
  branches:
    master:
      - step:
          name: build frontend
          image: node:lts
          script:
            - cd ./book-library
            - npm install
            - export REACT_APP_SERVER_URL=/api/
            - npm run build
          artifacts:
            - book-library/build/**
      - step:
          name: build backend
          image: mcr.microsoft.com/dotnet/core/sdk:3.1
          script:
            - mkdir book-library-api/book-library-api/wwwroot
            - cp -R book-library/build/* book-library-api/book-library-api/wwwroot
            - dotnet publish book-library-api/book-library-api/BookLibrary.API.csproj -c Release -o publish
          artifacts:
            - publish/**
      - step:
          name: build image
          script:
            - cd publish
            - docker build -t djziogas.lt:5443/library:v$BITBUCKET_BUILD_NUMBER .
            - docker push djziogas.lt:5443/library:v$BITBUCKET_BUILD_NUMBER
      - step:
          name: Deploy to kubernetes
          deployment: test
          image: atlassian/pipelines-kubectl
          # trigger: manual  # Uncomment to make this a manual deployment.
          script:
            - echo $KUBECONFIG | base64 -d > kubeconfig.yml
            - kubectl --kubeconfig=kubeconfig.yml set image deployment/library library=djziogas.lt:5443/library:v$BITBUCKET_BUILD_NUMBER

