// <auto-generated />
using System;
using BookLibrary.DataBase.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookLibrary.DataBase.Migrations
{
    [DbContext(typeof(LibraryDBContext))]
    [Migration("20200522203443_AddIdentityUsers")]
    partial class AddIdentityUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookLibrary.DataBase.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverPictureUrl")
                        .HasColumnName("CoverPictureURL")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("Date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("EditionLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Format")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoodReadsUrl")
                        .HasColumnName("GoodReadsURL")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Isbn")
                        .HasColumnName("ISBN")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("NumberOfPages")
                        .HasColumnType("int");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("Date");

                    b.Property<string>("Series")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("BookLibrary.DataBase.Models.BookCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("OfficeId");

                    b.ToTable("BookCase");
                });

            modelBuilder.Entity("BookLibrary.DataBase.Models.BookCaseComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookCaseId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("BookCaseId");

                    b.ToTable("BookCaseComment");
                });

            modelBuilder.Entity("BookLibrary.DataBase.Models.BookComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("BookComment");
                });

            modelBuilder.Entity("BookLibrary.DataBase.Models.BookWish", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<int>("Vote")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("BookWish");
                });

            modelBuilder.Entity("BookLibrary.DataBase.Models.Library", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("OfficeId");

                    b.ToTable("Library");
                });

            modelBuilder.Entity("BookLibrary.DataBase.Models.LibraryComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<int>("LibraryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.ToTable("LibraryComment");
                });

            modelBuilder.Entity("BookLibrary.DataBase.Models.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Office");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullAddress = "11d. Juozapaviciaus pr., Kaunas, LT-45252, Lithuania",
                            Name = "Kaunas"
                        },
                        new
                        {
                            Id = 2,
                            FullAddress = "135 Zalgirio g., Vilnius, LT-08217, Lithuania",
                            Name = "Vilnius"
                        },
                        new
                        {
                            Id = 3,
                            FullAddress = "8 Devonshire Square, London, EC2M 4PL, United Kingdom",
                            Name = "London"
                        },
                        new
                        {
                            Id = 4,
                            FullAddress = "36 Toronto Street Suite 260, Toronto, Ontario M5C 2C5, Canada",
                            Name = "Toronto"
                        },
                        new
                        {
                            Id = 5,
                            FullAddress = "350 N Orleans St, Suite 7500S, Chicago, IL 60654, United States",
                            Name = "Chicago"
                        });
                });

            modelBuilder.Entity("BookLibrary.DataBase.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookCaseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CheckedInOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("CheckedOutOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("PlannedReturnOn")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookCaseId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("BookLibrary.DataBase.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AspNetUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("GoodReadsAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<int?>("OfficeId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("AspNetUserId");

                    b.HasIndex("OfficeId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AspNetUserId = "b8c10928-5609-4d7c-8051-f0500b49fa0b",
                            Email = "nathan.roberts@gmail.com",
                            FullName = "Nathan Roberts",
                            GoodReadsAccount = "https://www.goodreads.com/",
                            IsAdmin = false,
                            OfficeId = 1,
                            PhoneNumber = "+3701234567",
                            ProfilePictureUrl = "https://randomuser.me/api/portraits/men/94.jpg",
                            Role = "Full-Stack Developer",
                            UserName = "Nathaniux123"
                        },
                        new
                        {
                            Id = 2,
                            AspNetUserId = "f6e4ac6a-d229-4e79-bb3d-1b58920918d7",
                            Email = "gmail@bean.mr",
                            FullName = "Mr. Bean",
                            GoodReadsAccount = "https://www.goodreads.com/",
                            IsAdmin = false,
                            OfficeId = 1,
                            PhoneNumber = "+3707654321",
                            ProfilePictureUrl = "https://vignette.wikia.nocookie.net/mrbean/images/4/4b/Mr_beans_holiday_ver2.jpg/revision/latest?cb=20181130033425",
                            Role = "Full-Time Disaster",
                            UserName = "Beanz"
                        },
                        new
                        {
                            Id = 3,
                            AspNetUserId = "09ecbf1a-320a-4633-b749-1960d7cb2804",
                            Email = "admin@library.com",
                            FullName = "Jon Mills",
                            GoodReadsAccount = "https://www.goodreads.com/admin-lib",
                            IsAdmin = true,
                            OfficeId = 1,
                            PhoneNumber = "+37010101010",
                            ProfilePictureUrl = "https://randomuser.me/api/portraits/men/34.jpg",
                            Role = "Full-Time Admin",
                            UserName = "MrAdmin"
                        });
                });

            modelBuilder.Entity("BookLibrary.DataBase.Models.UserWish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WishId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WishId");

                    b.ToTable("UserWish");
                });

            modelBuilder.Entity("BookLibrary.DataBase.Models.Waiting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookCaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookCaseId");

                    b.HasIndex("UserId");

                    b.ToTable("Waiting");
                });

            modelBuilder.Entity("BookLibrary.DataBase.Models.Wish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .IsUnique()
                        .HasFilter("[BookId] IS NOT NULL");

                    b.ToTable("Wish");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "52df1f1d-74a2-46e2-a8f4-c8ac24a75ea7",
                            ConcurrencyStamp = "52df1f1d-74a2-46e2-a8f4-c8ac24a75ea7",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "b8c10928-5609-4d7c-8051-f0500b49fa0b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d0c4d174-ab92-4b8a-b438-3801618fa132",
                            Email = "nathan.roberts@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "NATHAN.ROBERTS@GMAIL.COM",
                            NormalizedUserName = "NATHAN.ROBERTS@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBkEbCfAudIyZ0Qz/bx2Nr8toMPAuQf3RoCrNDswSwn5Tdn0ZNdfy/51Se1MsshULQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "SHNK3GMI3EAPFETOSCG36NR53ZYY3DN6",
                            TwoFactorEnabled = false,
                            UserName = "nathan.roberts@gmail.com"
                        },
                        new
                        {
                            Id = "f6e4ac6a-d229-4e79-bb3d-1b58920918d7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e0797c37-76cb-4814-b22e-de5344b5e2a0",
                            Email = "gmail@bean.mr",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "GMAIL@BEAN.MR",
                            NormalizedUserName = "GMAIL@BEAN.MR",
                            PasswordHash = "AQAAAAEAACcQAAAAEBkEbCfAudIyZ0Qz/bx2Nr8toMPAuQf3RoCrNDswSwn5Tdn0ZNdfy/51Se1MsshULQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "SHNK3GMI3EAPFETOSCG36NR53ZYY3DN6",
                            TwoFactorEnabled = false,
                            UserName = "gmail@bean.mr"
                        },
                        new
                        {
                            Id = "09ecbf1a-320a-4633-b749-1960d7cb2804",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "52df1f1d-74a2-46e2-a8f4-c8ac24a75ea7",
                            Email = "admin@library.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LIBRARY.COM",
                            NormalizedUserName = "ADMIN@LIBRARY.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBkEbCfAudIyZ0Qz/bx2Nr8toMPAuQf3RoCrNDswSwn5Tdn0ZNdfy/51Se1MsshULQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "SHNK3GMI3EAPFETOSCG36NR53ZYY3DN6",
                            TwoFactorEnabled = false,
                            UserName = "admin@library.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "09ecbf1a-320a-4633-b749-1960d7cb2804",
                            RoleId = "52df1f1d-74a2-46e2-a8f4-c8ac24a75ea7"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BookLibrary.DataBase.Models.BookCase", b =>
                {
                    b.HasOne("BookLibrary.DataBase.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLibrary.DataBase.Models.Office", "Office")
                        .WithMany()
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookLibrary.DataBase.Models.BookCaseComment", b =>
                {
                    b.HasOne("BookLibrary.DataBase.Models.BookCase", "BookCase")
                        .WithMany("BookCaseComment")
                        .HasForeignKey("BookCaseId")
                        .HasConstraintName("FK_BookCaseComments_BookCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookLibrary.DataBase.Models.BookComment", b =>
                {
                    b.HasOne("BookLibrary.DataBase.Models.Book", "Book")
                        .WithMany("BookComment")
                        .HasForeignKey("BookId")
                        .HasConstraintName("FK_BookComment_Book")
                        .IsRequired();
                });

            modelBuilder.Entity("BookLibrary.DataBase.Models.BookWish", b =>
                {
                    b.HasOne("BookLibrary.DataBase.Models.Book", "Book")
                        .WithMany("BookWish")
                        .HasForeignKey("BookId")
                        .HasConstraintName("FK_BookWish_BookId")
                        .IsRequired();
                });

            modelBuilder.Entity("BookLibrary.DataBase.Models.Library", b =>
                {
                    b.HasOne("BookLibrary.DataBase.Models.Book", "Book")
                        .WithMany("Library")
                        .HasForeignKey("BookId")
                        .HasConstraintName("FK_Library_BookId")
                        .IsRequired();

                    b.HasOne("BookLibrary.DataBase.Models.Office", "Office")
                        .WithMany("Library")
                        .HasForeignKey("OfficeId")
                        .HasConstraintName("FK_Library_OfficeId")
                        .IsRequired();
                });

            modelBuilder.Entity("BookLibrary.DataBase.Models.LibraryComment", b =>
                {
                    b.HasOne("BookLibrary.DataBase.Models.Library", "Library")
                        .WithMany("LibraryComment")
                        .HasForeignKey("LibraryId")
                        .HasConstraintName("FK_LibraryComment_LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookLibrary.DataBase.Models.Reservation", b =>
                {
                    b.HasOne("BookLibrary.DataBase.Models.BookCase", "BookCase")
                        .WithMany("Reservation")
                        .HasForeignKey("BookCaseId")
                        .HasConstraintName("FK_Reservation_BookCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLibrary.DataBase.Models.User", "User")
                        .WithMany("Reservation")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Reservation_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookLibrary.DataBase.Models.User", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "AspNetUser")
                        .WithMany()
                        .HasForeignKey("AspNetUserId");

                    b.HasOne("BookLibrary.DataBase.Models.Office", "Office")
                        .WithMany("User")
                        .HasForeignKey("OfficeId")
                        .HasConstraintName("FK_User_OfficeId");
                });

            modelBuilder.Entity("BookLibrary.DataBase.Models.UserWish", b =>
                {
                    b.HasOne("BookLibrary.DataBase.Models.User", "User")
                        .WithMany("UserWish")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserWish_UserId")
                        .IsRequired();

                    b.HasOne("BookLibrary.DataBase.Models.Wish", "Wish")
                        .WithMany("Votes")
                        .HasForeignKey("WishId")
                        .HasConstraintName("FK_UserWish_WishId")
                        .IsRequired();
                });

            modelBuilder.Entity("BookLibrary.DataBase.Models.Waiting", b =>
                {
                    b.HasOne("BookLibrary.DataBase.Models.BookCase", "BookCase")
                        .WithMany("Waiting")
                        .HasForeignKey("BookCaseId")
                        .HasConstraintName("FK_Waiting_BookCaseId")
                        .IsRequired();

                    b.HasOne("BookLibrary.DataBase.Models.User", "User")
                        .WithMany("Waiting")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Waiting_UserId")
                        .IsRequired();
                });

            modelBuilder.Entity("BookLibrary.DataBase.Models.Wish", b =>
                {
                    b.HasOne("BookLibrary.DataBase.Models.Book", "Book")
                        .WithOne("Wish")
                        .HasForeignKey("BookLibrary.DataBase.Models.Wish", "BookId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
