export const GET_LATEST_BOOKS = 'dashboard/GET_LATEST_BOOKS';
export const GET_LATEST_BOOKS_END = 'dashboard/GET_LATEST_BOOKS_END';
export const GET_CURRENTLY_READING_BOOKS =
  'dashboard/GET_CURRENTLY_READING_BOOKS';
export const GET_CURRENTLY_READING_BOOKS_END =
  'dashboard/GET_CURRENTLY_READING_BOOKS_END';
export const GET_RECOMMENDED_BOOKS = 'dashboard/GET_RECOMMENDED_BOOKS';
export const GET_RECOMMENDED_BOOKS_END = 'dashboard/GET_RECOMMENDED_BOOKS_END';
