export const GET_RESERVATIONS_START = "reservations/GET_RESERVATIONS_START";
export const GET_RESERVATIONS_END = "reservations/GET_RESERVATIONS_END";

export const GET_BOOK_RESERVATIONS_START =
  "reservations/GET_BOOK_RESERVATIONS_START";
export const GET_BOOK_RESERVATIONS_END =
  "reservations/GET_BOOK_RESERVATIONS_END";

export const ADD_RESERVATION_START = "reservations/ADD_RESERVATION_START";
export const ADD_RESERVATION_END = "reservations/ADD_RESERVATION_END";

export const UPDATE_RESERVATION_START = "reservations/UPDATE_RESERVATION_START";
export const UPDATE_RESERVATION_END = "reservations/UPDATE_RESERVATION_END";
